### PR TITLE
Prevent infinite recursion by breaking on outer loop. All unit tests pass.

### PR DESCRIPTION
**Pull request by ailabs-software**
I added a unit test which fails (infinite loop) on current jael, but passes with this change.

### CODE REVIEW

**Comment by thosakwe** [comment]
Hi, and thanks for sending this PR! This will be present in the next `2.x` release of Jael. I'll soon release a `3.x` which uses `reflectable` instead of mirrors, probably.

**Comment by ailabs-software** [comment]
Cool. That's a good idea.

I've already retrofitted a modified Jael to reflectable. Let me know if you want to see the code.

**Comment by thosakwe** [comment]
Hi, @bpilot! Thanks again for this PR.

All Angel subprojects have been consolidated into a single monorepo: https://github.com/angel-dart/angel.

Please fork the monorepo, and open a new PR there instead.

**Comment by thosakwe** [comment]
Hi, @bpilot! Thanks again for this PR.

All Angel subprojects have been consolidated into a single monorepo: https://github.com/angel-dart/angel.

Please fork the monorepo, and open a new PR there instead.

**Pull request closed without merging**
